### ISSUE TITLE
"Combat Extended" Blank Screen After Starting Up Game

### ISSUE THREAD

**Issue by LeninsCat** [cseelhoff/RimThreaded#504] opened 2021-05-03 00:20 UTC
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
Combat Extended and Rimthreaded immediately clash and any attempt at loading the game is tarnished and all that is displayed is a blank screen. I've redownloaded my mods and verified my files

**Steps to reproduce the behaviour **
1. Start the Game.
2. Game loads
3. Game turns to black

**Error Log**
https://gist.github.com/LeninsCat/3f3e037017f113ec2e9428b9cf65d5df

**Save file**
Not save

**Screenshots**
![image](https://user-images.githubusercontent.com/66055549/116831891-b620e880-ab77-11eb-9b29-591d4ff9ff3b.png)
Blank screen showing my problem.

[Mod list length: 6]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268]
RimPy Mod Manager Database [https://steamcommunity.com/sharedfiles/filedetails/?id=1847679158]
RimThreaded [1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Comment by pastorismylord** [comment] 2021-05-07 17:40
this was tested by @LeninsCat which is a tester.

**Comment by pastorismylord** [comment] 2021-05-17 21:28
@LeninsCat can you please add a savegame to the report?

**Comment by pastorismylord** [comment] 2021-05-23 07:14
was unable to reproduce said behaviour since 2.1.1, testing with 2.2.5 did not produce the issue.

**Comment by pastorismylord** [comment] 2021-05-25 17:06
fixed on preview

**Closed** 2021-06-19 04:14 UTC
Labels: 1.3.1 - 1.3.2, Bug, Confirmed, Fixed In Preview, Mod Incompatibility, Reproducible
