### ISSUE TITLE
Roads aren't drawn on local map during map generation

### ISSUE THREAD

**Issue by Lt-Bob** [cseelhoff/RimThreaded#473] opened 2021-02-26 02:13 UTC
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
Roads aren't drawn on local map during map generation

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Remove all mods other than Rimthreaded
2. Start a new game
3. After world generation, pick a map tile that has a road on it
4. Road will not be present
5. Remove RimThreaded from modlist
6. Start a new game
7. After world generation, pick a map tile that has a road on it
8. Road will be present on local map

**Error Log**
Does not throw any errors, road is just missing

**Save file**
[Saves (With and Without RimThreaded).zip](https://github.com/cseelhoff/RimThreaded/files/6046988/Saves.With.and.Without.RimThreaded.zip)

**Screenshots**
![Without RT](https://user-images.githubusercontent.com/62475308/109245271-00ab7080-7795-11eb-94d7-b5f015d80a50.jpg)
![With RT](https://user-images.githubusercontent.com/62475308/109245283-03a66100-7795-11eb-869e-38776146d0c2.jpg)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty
* RimThreaded

**Comment by Eldulac** [comment] 2021-03-15 14:56
**[Tested on RT 1.3.2]**
I tested this issue on a fresh game, and was able to replicate it. The roads are not being generated on a local map.
I also received two kinds of errors in the log:

https://gist.github.com/Eldulac/99cafb6ced7e6e3f8d3cd08d6860edb7
https://gist.github.com/Eldulac/2eb60a52913663b725509674b6de051a (This error only happened on asphalt roads)

**Here is the HugsLib log:**
https://gist.github.com/HugsLibRecordKeeper/5ff0a55942bbcc156c541433c89a27f3

[Road Generation Issue.zip](https://github.com/cseelhoff/RimThreaded/files/6142160/Road.Generation.Issue.zip)

I tested this on different road types and biomes. The results were always the same, except one of the errors only happens on asphalt roads.

**Conclusion**
This issue is confirmed. It only happens with RT, and it happens every time and on every type of road.

**Comment by Niilo007** [comment] 2021-04-29 19:05
Tested in 2.0.7
i tested a map with asphalt road and the road didn't generate

**Comment by cseelhoff** [comment] 2021-05-14 02:18
Seems to work fine in 2.1.4
![image](https://user-images.githubusercontent.com/22664374/118210875-1c8bed80-b439-11eb-9530-4029322513da.png)

**Comment by cseelhoff** [comment] 2021-05-14 02:30
Fixed in 2.1.5

**Comment by pastorismylord** [comment] 2021-05-15 04:58
to confirm the resolution of this issue several tests were ran: 

Test 1:

- Downloaded the attached save.
- proceeded to load the save with rimthreaded 2.1.5.

Due to the state of the save, no roads were shown.

Test 2:

- Initiated a new game.
- Generated a new world.
- Selected a road tile as the starting colony

In this scenario, the road was properly generated.

Test 3:

- loaded another game
- started a caravan
- created another colony on a road tile

in this scenario, the road was properly generated.

**Closed by pastorismylord** 2021-05-15 04:58 UTC
Labels: 1.3.1 - 1.3.2, 2.0.6 - 2.0.7, Bug, Confirmed, Fix Needs Testing, Good First Issue, Reproducible, Vanilla RT
