### ISSUE TITLE
The shuttle can't take off. 

### ISSUE THREAD

**Issue by ViciousCC** [cseelhoff/RimThreaded#615] opened 2021-08-10 21:39 UTC
The shuttle can't take off. There's no take off button

Modlist:

![image](https://user-images.githubusercontent.com/56225660/128938453-7457ad66-88c3-4638-983e-bc46281ae0f1.png)

Bug:
![image](https://user-images.githubusercontent.com/56225660/128938401-a635d349-9bc0-4c29-b7a8-817da648eb7d.png)

**Comment by Pustalorc** [comment] 2021-08-11 12:44
Use build 2.5.8.2 from the discord:
https://discord.com/channels/754090371654483999/754090372317052961/871635771092774922

Duplicate of #597 
Requesting close.

**Closed** 2021-08-14 16:10 UTC
Labels: Bug, Reproducible, Vanilla RT
