### ISSUE TITLE
Relation modifiers reset upon loading a saved game.

### ISSUE THREAD

**Issue by Eldulac** [cseelhoff/RimThreaded#490] opened 2021-03-18 12:08 UTC
**Describe the bug**
When playing a game with RT, whenever you load a saved game, the relation modifiers section fails to reproduce itself.
All the temporary modifiers, such as ChitChat and Deep talk, are lost. Only the permanent modifiers remain, such as Friend, Lover, Spouse etc. Presumably these permanent modifiers are generated again once the game has loaded itself.

This resetting seems to happen upon loading a game, and not upon saving it. I tested this by saving a game with RT loaded. Then reloading the save without RT. In these cases the temporary modifiers were present, and no issues were found.

No errors were encountered relating to this issue.

Finally, this was also tested on the experimental 2.0 version. The issue still persists.

**Steps to reproduce the behavior**
1. Start a game
2. Wait until pawns have done Chitchat or deep talk
3. Save game
4. Load game
5. The social tab should be void of temporary modifiers

**Save File**
[ChitChat problem.zip](https://github.com/cseelhoff/RimThreaded/files/6163814/ChitChat.problem.zip)

**Mod list**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Mod Manager
* RimThreaded

**Comment by bababooeyy** [comment] 2021-03-28 05:27
occurs on preview 2.0.5

**Comment by bababooeyy** [comment] 2021-04-25 12:45
occurs on preview 2.0.7

**Comment by Niilo007** [comment] 2021-04-30 18:53
before save & load
![image](https://user-images.githubusercontent.com/75486261/116741003-6cf95900-a9fe-11eb-9c5f-c3c71072cd01.png)

after save & load
![image](https://user-images.githubusercontent.com/75486261/116741045-7c78a200-a9fe-11eb-8947-1fc591b72bd1.png)

**Comment by Niilo007** [comment] 2021-04-30 18:57
attempt 2

before
![image](https://user-images.githubusercontent.com/75486261/116741546-f27d0900-a9fe-11eb-81d2-07fe75831b72.png)

after
![image](https://user-images.githubusercontent.com/75486261/116741591-fe68cb00-a9fe-11eb-8efc-1817f5ae9e27.png)

**Comment by 15adhami** [comment] 2021-05-01 02:24
Was not able to reproduce in 2.0.7. Tested a few times with a heavily modded save, and a few times with a new vanilla colony.

**Comment by Niilo007** [comment] 2021-05-15 22:12
Zeros tested this with the newest preview, bug seems to be fixed

**Comment by pastorismylord** [comment] 2021-06-19 17:19
re-opening as there are reports of this issue emerging on latest 2.3 steam release

**Comment by pastorismylord** [comment] 2021-08-14 16:13
should be fixed now

**Closed by pastorismylord** 2021-08-14 16:13 UTC
Labels: Bug, Reproducible, Vanilla RT, Confirmed, Game Breaking, 1.3.x, 2.0.x, 2.2.x
