### ISSUE TITLE
Temp change to outside temp when destroying a wall

### ISSUE THREAD

**Issue by seniorkiller** [cseelhoff/RimThreaded#409] opened 2021-01-23 11:55 UTC
**Describe the bug**
temp of a room change to outside temp when remove a block or wall or stone in that room
someone on RT discord server say it may bc RegionAndRoomUpdater was overhauled
**To Reproduce**
1. Start the game
2. Make a room that have different temperature from outside temp
3. destroy or mine a wall or stone in the room
4. done

**Error Log**
https://gist.github.com/8a170dfc701a110ba7d416d9c5991e04
just to make sure
https://gist.github.com/1522e6ae4158d7304110c62e38f47c84

**Screenshots**
![Screenshot 2021-01-23 185431](https://user-images.githubusercontent.com/77882062/105577473-75614880-5dac-11eb-8299-57e5d4f7d9fb.png)

![Uploading image.png…]()

**Comment by thefriendlycacti** [comment] 2021-01-25 23:42
I am able to reproduce this will the following mods following this order:
Harmony
Core
HugsLib
RimThreaded(1.2.4)

Hugs Lib Log: https://gist.github.com/HugsLibRecordKeeper/d7b1f1b855bea0d414059b7d5f15205a

I can confirm when I build or destroy walls, doors, or nutrient paste dispensers, the temperature inside of the room becomes set to the current map temperature. I assume this might be due to the way rooms are handled.

**Comment by kerdv** [comment] 2021-01-28 00:39
Same result when stone walls are smoothed.

**Comment by Niilo007** [comment] 2021-02-03 14:40
fixed in 1.2.7 re open if it happens again

**Closed by Niilo007** 2021-02-03 14:40 UTC
Labels: 1.2.0 - 1.3.0, Bug, Confirmed Bug, Reproducible, Vanilla RT
