### ISSUE TITLE
(2.2.8) A psychic droner tuned to the None gender is driving Nones mad

### ISSUE THREAD

**Issue by GitHubDeadTree** [cseelhoff/RimThreaded#434] opened 2021-02-03 10:49 UTC
**Describe the bug**
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  

* bug description here !!!
*once there is Ship part(psychic droner) or Psychic suppressor ,it will lose effectiveness and there is no red error
but if i use dev mod to change its gender mode, it will back to normal
*actually the same bug appear in my other save with 100+ mods

**To Reproduce (VERY IMPORTANT)**
1.just wait until the event appear

**Error Log**
* Link to contents of Player.log or Error.log (MUST BE LINK)
* Link to HugsLib log. (MUST BE LINK)
* Sorry i cant find a error log

**Screenshots**
* If applicable, add screenshots to help explain your problem.
* 
![20210203182034_1](https://user-images.githubusercontent.com/77949417/106736099-fc85aa80-664f-11eb-9418-fa96eefc8d31.jpg)
![20210203182037_1](https://user-images.githubusercontent.com/77949417/106736117-00b1c800-6650-11eb-8b26-bc788fec4b87.jpg)
![20210203182041_1](https://user-images.githubusercontent.com/77949417/106736121-027b8b80-6650-11eb-9c50-0bcf09a9b8f8.jpg)
![20210203182046_1](https://user-images.githubusercontent.com/77949417/106736127-04454f00-6650-11eb-92c5-fc7e8da7ffc4.jpg)
![20210203183442_1](https://user-images.githubusercontent.com/77949417/106736200-1d4e0000-6650-11eb-985c-22918ea92234.jpg)
![20210203183416_1](https://user-images.githubusercontent.com/77949417/106736209-1fb05a00-6650-11eb-8014-7fcddd7ee095.jpg)

**Comment by Nextia-Git** [comment] 2021-02-25 13:58
Recently had this happen on my save and am unsure of the cause so it still is very much a problem in the current version of 1.3.2.
Psychic droner landed and is currently tunes to the (none) gender, but as soon as it ramps up to Medium, it "fixes" it's self and is now tuned to (male). 
Info pannel when clicked on states the correct gender but the info by the letters states otherwise as (none), and male pawns did not have the mood penalty until it increased to medium.

[https://imgur.com/cIedubZ](url)
[https://imgur.com/3VM9HPT](url)

No point attaching a log as there isn't anything of note when it changes to medium, and nothing else mentioning the psychic droner appears. Save file and modlist included below though-

Save file:https://mega.nz/file/pgYyGbLA#DlYTfovjnpEAoTqohJGoffeHzusr1IajPTH_voGAR6g
Modlist:https://mega.nz/file/FoJgHb5Y#UL6Dn_Gkud1533e-AX01_b0a2jnsVCXHvMejbzQ0aBQ

**Comment by Nextia-Git** [comment] 2021-02-28 19:39
Occured again this time with a Royalty Psychic Droner but essentially the exact same situation. Changing the droner to High again gives it the correct gender shown in the tooltip.

![b698a56112659bca4bf024176273bda5](https://user-images.githubusercontent.com/10771689/109431034-5f265800-79fc-11eb-9bc4-058bfd6ecd52.jpg)

[The Heated Wasters#§#The Heated Wasters Psychic Droner Bug V2.zip](https://github.com/cseelhoff/RimThreaded/files/6057814/The.Heated.Wasters.The.Heated.Wasters.Psychic.Droner.Bug.V2.zip)

**Comment by Niilo007** [comment] 2021-05-01 18:11
confirmed in 2.0.7
![image](https://user-images.githubusercontent.com/75486261/116791268-bced2400-aac1-11eb-8671-2b8133188dc9.png)
ship part says "male" but the colonists are not affected.

**Comment by Niilo007** [comment] 2021-05-19 18:10
![image](https://user-images.githubusercontent.com/75486261/118862670-aa0e8800-b8e6-11eb-954c-b598473762fb.png)

Happens in 2.1.5

**Comment by pastorismylord** [comment] 2021-05-24 03:04
[test2.zip](https://github.com/cseelhoff/RimThreaded/files/6529544/test2.zip)
Tested this issue with 2.2.8 and this additional save named test2.
I triggered the psychic ship part event via the debug menu, the issue still persists.

**Comment by 15adhami** [comment] 2021-05-31 14:30
Confirmed in 2.2.19. Created a new save file, and used devmode to spawn a psychic ship.

**Comment by pO0P3R125** [comment] 2021-06-18 02:24
Still happens in RT 2.3.6.7
Created new map and summoned psychic ship, it displays male but no male pawn in colony is affected

**Comment by cseelhoff** [comment] 2021-08-16 15:05
fixed in 2.5.12

**Closed by cseelhoff** 2021-08-16 15:05 UTC
Labels: Bug, Reproducible, Vanilla RT, Confirmed, 1.3.X.X, 2.0.X.X, 2.2.X.X, 2.5.11
