### ISSUE TITLE
a tile that should be permament winter always reports as spring

### ISSUE THREAD

**Issue by kerdv** [cseelhoff/RimThreaded#491] opened 2021-03-20 03:49 UTC
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**  When Regrowth and RT are loaded.
On a tile whose season should be permanent winter, it seems to be stuck on Spring for me.  

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Create a game with 100% coverage on a very cold map
2. Create a new colony near the north pole, mine was mountainous ice sheet, mine was -11-110f
3. Instead of reporting permanent winter, the season locks in at Spring.
4. Remove RT, game reports permanent winter.

**Error Log**
https://gist.github.com/3f18833a2c710e75d16297eacf278be0

**Save file**
Added save file and player.log into attached z
[regrowth issue.zip](https://github.com/cseelhoff/RimThreaded/files/6174845/regrowth.issue.zip)
ip

**Screenshots**
!!! Add screenshots to help explain your problem here !!!

**Have you done any changes to the community mod list?**  
!!! YES / NO !!! Yes, added ones from the discord marked as compatible. 
[regrowth issue.zip](https://github.com/cseelhoff/RimThreaded/files/6174842/regrowth.issue.zip)

**Mod list (Preferably a RimPy compatible list.)**
https://rentry.co/nwwn8

**Comment by Niilo007** [comment] 2021-03-20 10:57
one thin to note, is that the north pole does indeed have seasons, including spring. bit if the season was indeed stuck at spring, then that would be odd.

second thing. Was this indeed with the community mod pack? if it was with some other mod list, you should not select this template

**Comment by kerdv** [comment] 2021-03-20 14:00
They don't in vanilla.  If I remove RT, the map reverts to calling the season "permanent winter".

Line 92 of https://github.com/pastorismylord/Community-Modpack/blob/main/Community-modpack.xml

**Comment by 15adhami** [comment] 2021-04-15 21:46
Tested with RT 1.3.2 and 2.0.7. Was only able to reproduce with 1.3.2, and the issue happens even without [HLX] Regrowth - Core loaded. Loading an ice sheet tile near the north pole resulted in the season being Spring with RT loaded, loading the same tile without RT results in permanent winter. Seems to be fixed in 2.0.7.

**Closed** 2021-06-19 04:14 UTC
Labels: 1.3.1 - 1.3.2, Bug, Confirmed, Fixed In Preview, Reproducible, Vanilla RT
