### ISSUE TITLE
UI Disappearing on Doors/areas

### ISSUE THREAD

**Issue by VashSevrem** [cseelhoff/RimThreaded#244] opened 2020-11-20 16:44 UTC
**Describe the bug**
When building walls and doors A random root level exception in OnGUI() is thrown. 

**To Reproduce**
Yes, building walls and doors in close proximity will produce this bug.

1. Set up walls and doors.
2. Assign all workers capable of building and max out skills to speed it up.
3. If error does not occur set up more doors and walls closer together.

**Error Log**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5574893/Player.log)

**Mod List**
Harmony
Rimworld
Rimthreaded

**Screenshots**
https://i.gyazo.com/22f51cbf006d2cfcc211fca6a4ec7a1b.gif

**Comment by cseelhoff** [comment] 2020-11-23 04:30
I am unable to reproduce, but I do believe this issue was fixed in one of the recent releases. Please reopen if it continues to occur.

**Closed by cseelhoff** 2020-11-23 04:30 UTC
Labels: bug, reproducible, vanilla

**Comment by VashSevrem** [comment] 2020-11-24 16:31
Yea I was unable to reproduce as well Rimthreaded is running great, Great Job!
