### ISSUE TITLE
"Party" event errors (needs to be tested 1.2.7)

### ISSUE THREAD

**Issue by Niilo007** [cseelhoff/RimThreaded#417] opened 2021-01-26 18:05 UTC
**Describe the bug**
During the "Party" event there are errors

**To Reproduce**
1. Load any save
2. Wait for a "Party" event / trigger it with dev-mode
3. See red errors in log

**Comment by bababooeyy** [comment] 2021-01-28 09:07
I shall just leave a save and logs here if its useful lol. 
https://gist.github.com/775a4a17603339ce86fe5e21d807c32d

Save: 
https://drive.google.com/file/d/1zqX3td5lJLpI9SLFQVPXYhtLNDmCAmsg/view?usp=sharing

**Comment by bababooeyy** [comment] 2021-01-30 04:56
Can confirm still happens in 1.2.6

**Comment by cseelhoff** [comment] 2021-02-01 13:53
this seems to be fixed with 1.2.7

**Comment by bababooeyy** [comment] 2021-02-02 01:12
Confirmed fixed

**Closed** 2021-02-02 12:08 UTC
Labels: >1.2.6, Bug, Fix Needs Testing, Reproducible, Vanilla RT
