### ISSUE TITLE
Could not load UnityEngine.Texture2D

### ISSUE THREAD

**Issue by AGingersaurusRex** [cseelhoff/RimThreaded#134] opened 2020-09-19 23:15 UTC
Any time I craft apparel I get this red error. I don't know if anyone else has reported this.

https://gist.github.com/AGingersaurusRex/200aebef563f3db8fb36f9b7f2c48b89

**Comment by cseelhoff** [comment] 2020-09-21 17:39
Nice job finding this, if it is indeed reproducible. I've been trying to hunt this one for a while.

**Comment by cseelhoff** [comment] 2020-11-23 04:41
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.

**Closed by cseelhoff** 2020-11-23 04:41 UTC
Labels: bug, reproducible
