### ISSUE TITLE
"Biomes! Islands" Exception ticking AEXP_RedPanda69651 (at (290, 0, 132)): System.IndexOutOfRangeException: index + length > size   at System.Array.Clear

### ISSUE THREAD

**Issue by Artembelov** [cseelhoff/RimThreaded#453] opened 2021-02-09 01:45 UTC
**Describe the bug**
Exception ticking (insert living thing here) System.IndexOutOfRangeException at System.Array.Clear

* bug description here !!!
Generates out of range exceptions until it crashes to desktop doesn't post what's actually wrong to DNspy before it crashes

**To Reproduce (VERY IMPORTANT)**
Load game with modpack and start map

**Error Log**
https://gist.github.com/b48f39e236402db73e36684fa5dc4ba4

**Mod List**
https://pastebin.com/JE87ts7i

**Screenshots**
https://ibb.co/jGQGzYN

Hoff ill be on every night just DM me when you are ready to remote my computer so you can take a look at it
-Judd

**Comment by cseelhoff** [comment] 2021-02-09 04:47
Biomes Mod is incompat

**Comment by MadPacMan** [comment] 2021-02-09 08:40
Duplicate of https://github.com/cseelhoff/RimThreaded/issues/256

**Comment by pastorismylord** [comment] 2021-05-25 04:55
there's a duplicate issue already open. Closing this one as it's not tracking additional details.

**Closed by pastorismylord** 2021-05-25 04:55 UTC
Labels: 1.3.1 - 1.3.2, Bug, Confirmed, Duplicate, Mod Incompatibility, Reproducible
