### ISSUE TITLE
Could not execute post-long-event action. Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by Firebirdss80** [cseelhoff/RimThreaded#76] opened 2020-09-12 01:40 UTC
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Verse.LongEventHandler.ExecuteToExecuteWhenFinished () [0x00072] in <d72310b4d8f64d25aee502792b58549f>:0 
Verse.Log:Error(String, Boolean)
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:ExecuteWhenFinished(Action)
Verse.Pawn_AgeTracker:Verse.Pawn_AgeTracker.RecalculateLifeStageIndex_Patch1(Pawn_AgeTracker)
Verse.Pawn_AgeTracker:get_CurLifeStageIndex()
Verse.Pawn_AgeTracker:get_CurLifeStageRace()
Verse.Pawn_AgeTracker:get_CurLifeStage()
Verse.Pawn:get_HealthScale()
Verse.HediffSet:CalculateBleedRate()
Verse.HediffSet:get_BleedRateTotal()
Verse.Pawn_HealthTracker:HealthTick()
Verse.Pawn:Tick()
RimThreaded.Ticklist_Patch:ProcessTicks()
RimThreaded.<>c:<CreateTickThreads>b__26_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by cseelhoff** [comment] 2020-09-12 01:44
duplicate of #15 I think

**Closed** 2020-09-12 01:45 UTC
Labels: duplicate

**Comment by cseelhoff** [comment] 2020-09-12 02:17
Thanks for the submission! I really do appreciate it! If you don't thinks its a duplicate, please reopen!
