### ISSUE TITLE
Thread Error when 2 counts meditate on 2 thrones inside one room

### ISSUE THREAD

**Issue by geojak** [cseelhoff/RimThreaded#498] opened 2021-04-07 18:40 UTC
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  
Checked, there doesent seem to be a similiar open issue yet

**Describe the bug**
In my long going safe when i got my 2 counts both meditate at the same time in their joint throne room on two the two thrones inside there, then the threads crash and wont finish repeteadly until one guy stops meditating. this causes massive lag.

If one guy uses the small throne and one guy the big throne then no errors appear.

Removing rimthreadded prevents any errors.

putting the 2 thornes into 2 differnt rooms prevents the error

Unfortunelty i wasnt able to reproduce the error on a new safe with  similair sitaution with pawns meditating.

this safe was played with many mods and things might have been broken over time. in the first comment below i have uploaded the safe and logs after i removed all mods but one faction xml mod. the error persisted.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Load my Safe
2. Have my 2 counts both mediate at the same time in my throne room with the big thrones (not the small one)

**Error Log**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/6273805/Player.log)
[Hugliblog.txt](https://github.com/cseelhoff/RimThreaded/files/6273848/Hugliblog.txt)

**Save file**

[bug2.zip](https://github.com/cseelhoff/RimThreaded/files/6273816/bug2.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/25199983/113917031-fdb68d80-97e0-11eb-9790-21a4386c37b4.png)

**Mod 

list (Preferably a RimPy compatible list.)**
[modlist.zip](https://github.com/cseelhoff/RimThreaded/files/6273817/modlist.zip)

**Comment by geojak** [comment] 2021-04-07 19:18
I managed to remove all mod but one xml faction mod from my safe and still reproduce the error.
[Hugliblog2.txt](https://github.com/cseelhoff/RimThreaded/files/6273960/Hugliblog2.txt)
[Player2.log](https://github.com/cseelhoff/RimThreaded/files/6273961/Player2.log)
[bug3.zip](https://github.com/cseelhoff/RimThreaded/files/6273969/bug3.zip)

the modlist is now 
harmony
core 
royaltry
myGunpowder
Rimthreaded

myGunpoweder is my version of vanilla medieval expadned. it is basically all the xml stuff minus all the rest. you wont be ablte to run the safe without it because of the faction then crashng the game on load. you might be even able to use vanilla faction expanded medieval instead. my version has onlz one assebly. that is the nocamshakeexplsoion.dll. this really should matter here. its as close to vanilla as it can get.


[MyGunpowder.zip](https://github.com/cseelhoff/RimThreaded/files/6273974/MyGunpowder.zip)

**Comment by Niilo007** [comment] 2021-04-20 08:52
https://steamcommunity.com/workshop/filedetails/discussion/2222907981/3171072251352128458/?tscn=1618814281

**Comment by 15adhami** [comment] 2021-04-20 10:58
Tested in RT 1.3.2 and 2.0.7. Was able to reproduce the thread timeouts in 1.3.2, but it seems to be fixed in 2.0.7. However, there was still massive error spam in 2.0.7 even without 2 pawns meditating at the same time. Could be due to the removal of all your other mods? Log: https://gist.github.com/HugsLibRecordkeeper2/784f262bda5f912c1dcc8ef190157fd3

**Comment by geojak** [comment] 2021-04-22 18:18
checked the log, not sure what causes these error spamms but must be a removed mod as i have plazed this safe much more in the meantime with the full original modlist without getting these. if 2.07 fixed this i am reallz looking forward

**Comment by pastorismylord** [comment] 2021-06-07 18:28
@geojak this issue should be fixed on 2.2.19 preview which is available to download on our discord server, on the releases channel. Take a look and let us know, thanks!

**Comment by geojak** [comment] 2021-06-07 20:48
i will give it a try, bit bussy playing wow at the moment. will comment back next weekend!

**Comment by geojak** [comment] 2021-06-11 13:25
> 
> 
> @geojak this issue should be fixed on 2.2.19 preview which is available to download on our discord server, on the releases channel. Take a look and let us know, thanks!

Hi pastorismyord,

the Issues appears to be fixed with 2.1.9 from discord. I was not able to reproduce the issue anymore on the same file with the otherwise ideticall modlist (i keep my mods all local so random steam updates cant disturb my safes)

Thank your for the support and fix, it is very appreciated!

**Closed** 2021-06-19 04:14 UTC
Labels: 1.3.1 - 1.3.2, Bug, Confirmed, Fixed In Preview, Reproducible
