### ISSUE TITLE
Could not register region

### ISSUE THREAD

**Issue by SosukeAizen** [cseelhoff/RimThreaded#387] opened 2021-01-04 05:56 UTC
**Describe the bug**
Set some floors to be constructed outside of dining room, at some point pawns went into it and couldn't move any more. Edit: Actually seems like an issue with the room the prisoner was in, he died of starvation and both pawns are stood on top of food. I had to remove some wall and rebuild to fix the issue.

**To Reproduce**

**Error Log**
https://gist.github.com/SosukeAizen/9f0fbf66f8854922440030b59500e784
https://gist.github.com/SosukeAizen/c333b9cf9ea662d888de52a16018bbf0

**Screenshots**
![image](https://user-images.githubusercontent.com/15948761/103504872-950dec80-4e50-11eb-83e4-10df07f1a5bb.png)

**Comment by Pandemic223** [comment] 2021-01-15 21:16
[2021-01-15 16-07-32-1.zip](https://github.com/cseelhoff/RimThreaded/files/5822936/2021-01-15.16-07-32-1.zip)

**Comment by bababooeyy** [comment] 2021-01-30 12:28
Spent something like an hour and a half testing this and the method in the video to reproduce the bug in 1.2.6 RT, didn't get it once. 

poG

**Comment by Niilo007** [comment] 2021-01-31 15:50
seems to be fixed in 1.2.6

**Closed by Niilo007** 2021-01-31 15:50 UTC
Labels: Accepted For Testing, Bug, Path Finding, Reproducible, Vanilla RT
