### ISSUE TITLE
ThinkNode_Tagger TryIssueJobPackage (x4 speed, 9000 TPS)

### ISSUE THREAD

**Issue by ColourlessAmiba** [cseelhoff/RimThreaded#388] opened 2021-01-04 18:37 UTC
**Describe the bug**
I know this isn't helpful, but the bug itself doesn't seem, to hinder gameplay in any noticeable way, and I'm not skilled enough to decipher debug messages, so I'm not quite sure what the issue exactly is.

CURRENTLY UNSURE IF IT IS A MODDED ISSUE OR IF IT CAN BE REPLICATED IN VANILLA+RIMTHREADED.

**To Reproduce**
The mods I ran were essentially every single Vanilla Expanded mod you can download from the workshop.
Clicked new game
Selected the Mechanoid storyteller
Selected Arid Shrubland 
Ran at x4 speed and waited to see if malnutrition of an animal was causing the null exception, but ran into 200+ ThinkNode_Tagger errors instead.

**Error Log**
(https://github.com/cseelhoff/RimThreaded/files/5766185/ThinkNode_Tagger.Debug.Message.List.txt)

**Mod List**
(https://user-images.githubusercontent.com/76966909/103567452-167d7300-4e81-11eb-8737-4e459f865f8c.jpg) (1)
(https://user-images.githubusercontent.com/76966909/103567484-26955280-4e81-11eb-80d0-e9f51c375f8b.jpg) (2)
(https://user-images.githubusercontent.com/76966909/103567491-2b5a0680-4e81-11eb-8d25-4e21bbffa916.jpg) (3)

**Screenshots**
(https://cdn.discordapp.com/attachments/789343958727786557/795719045596577822/20210104112318_1.jpg)

**Comment by ColourlessAmiba** [comment] 2021-01-04 18:38
MODLIST
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - majorhoff.rimthreaded
  - VanillaExpanded.VFEFarming
  - VanillaExpanded.VAETS
  - VanillaExpanded.VAEAU
  - VanillaExpanded.VAETR
  - VanillaExpanded.VFESecurity
  - VanillaExpanded.VAEBF
  - VanillaExpanded.VAEIS
  - VanillaExpanded.VAET
  - VanillaExpanded.VFEProduction
  - VanillaExpanded.VAEED
  - VanillaExpanded.VAED
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VAECD
  - VanillaExpanded.VAEAS
  - VanillaExpanded.VFEPropsandDecor
  - VanillaExpanded.VFECore
  - rimsenal.EVP
  - VanillaExpanded.VPlantsE
  - VanillaExpanded.VCookEStews
  - VanillaExpanded.VPlantsESucculents
  - VanillaExpanded.VBrewE
  - VanillaExpanded.VCookESushi
  - VanillaExpanded.VCookE
  - VanillaExpanded.VFEArt
  - VanillaExpanded.VHE
  - VanillaExpanded.VFEPower
  - VanillaExpanded.VWE
  - VanillaExpanded.VHE.Beards
  - VanillaExpanded.VWEL
  - VanillaExpanded.VWEQ
  - VanillaExpanded.VTEXE
  - VanillaExpanded.VFESpacer
  - VSE.IgorInvader
  - VSE.PerryPersistent
  - VanillaExpanded.VBooksE
  - VanillaExpanded.VWEG
  - VanillaExpanded.VWEHW
  - VanillaExpanded.VanillaTraitsExpanded
  - OskarPotocki.VanillaFactionsExpanded.Core
  - OskarPotocki.VFE.Mechanoid
  - VanillaExpanded.VAETF
  - VanillaExpanded.VBrewECandT
  - paradox.morevanillaturrets
  - VanillaExpanded.VEE
  - VanillaExpanded.VCEF
  - VanillaExpanded.VAPPE
  - VanillaExpanded.VARME

**Comment by Niilo007** [comment] 2021-01-26 15:13
Your rimthreaded should be at the bottom of the list.

**Comment by bababooeyy** [comment] 2021-01-28 14:25
I managed to replicate this in vanilla, with *maybe* the null-reference exception you're talking about as well.

Null-reference exception log:
https://gist.github.com/60d9705db3be0f2164dd175d558bbad6

ThinkNode_Tagger errors:
https://gist.github.com/9d68c847240a14d88c1b266122d99011

Save File:
https://drive.google.com/file/d/1Kis4qDJwVczw8LncwJSPmnns1Fk4hzam/view?usp=sharing

**Comment by pastorismylord** [comment] 2021-02-09 19:08
@bababooeyy can you please confirm if this issue still exists with the latest version of RT?

**Comment by bababooeyy** [comment] 2021-02-11 06:07
No longer happens in 1.3.1.3 on the save I provided or a new save that I tried it on. There seems to be an increase in 

**these errors**
[Error 1.txt](https://github.com/cseelhoff/RimThreaded/files/5963365/Error.1.txt)

There is, however, a string of errors that did not appear before. These are attached in a single file 

**here**
[New Errors.txt](https://github.com/cseelhoff/RimThreaded/files/5963369/New.Errors.txt)
I am assuming the second one was a failsafe put in by Hoff to prevent error spam like before.

Would suggest reading through the entire log though, as it's not that long and there are some interesting errors there that might be important. 

https://gist.github.com/b926748cb297dc853c3118fe3f4c56ca

**Comment by pastorismylord** [comment] 2021-05-23 07:26
Unable to reproduce with 2.2.5 using provided saves.

**Comment by pastorismylord** [comment] 2021-05-24 03:22
tested again with 2.2.8

Used existing save file to reproduce the issue by making sure all the food supplies were blocked for colonists.
Colonists died of malnutrition without triggering any errors. I'll consider this issue fixed in the 2.1.x codetrain.

**Closed** 2021-06-19 04:14 UTC
Labels: 1.3.1 - 1.3.2, Bug, Confirmed, Fixed In Preview, Reproducible, Vanilla RT
