### ISSUE TITLE
Harvesting causes colonists to break (Hydroponics)

### ISSUE THREAD

**Issue by SethDusek** [cseelhoff/RimThreaded#583] opened 2021-06-28 02:32 UTC
**Describe the bug**
If you have fully matured plants and your colonists go to harvest them, the game will spit out some errors and will break their behaviour. Afterwards, colonists seem to stand around instead of wandering, and only move if they have some job. This seems to be caused by the fix in 2.4.3 to fix the previous bug in 2.4.2 #581 

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Plant some crops (**EDIT**: Plant some crops in a hydroponics bench)
2. Wait for them to be fully grown
3. Have colonists assigned to Plant Cutting, do not manually give them the job priority but have them do it on their own
4. The debug log should open up with red errors

**Error Log**

https://gist.github.com/HugsLibRecordKeeper/686fa589155bfbb7fd0938bfa8d80d56
**Save file**
https://gist.github.com/SethDusek/e78dad2420f02457d5b819fa748b7bd2 Load this savefile, wait for the plants to fully grow and wait. 
**Screenshots**
![image](https://user-images.githubusercontent.com/9436380/123569940-b5f04280-d7e0-11eb-8d29-95e2fae6c2d8.png)
**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* RimThreaded
* HugsLib

**Comment by kerdv** [comment] 2021-06-28 22:19
I seem to be having this issue as well, particularly with Hydroponics.  I create a vanilla save for this, first planting went properly but when the first crop matured I got the 10x jobs error.  Bug report:  https://gist.github.com/16a7696f534b408f4e4350c7bd09ee19  Save file attached.  Let the game run until the rice harvests, the pawn will freeze when switching from harvesting mature rice to replanting new ones.

[Hydroponics test save.zip](https://github.com/cseelhoff/RimThreaded/files/6729533/Hydroponics.test.save.zip)

**Comment by SethDusek** [comment] 2021-06-29 08:47
After some more testing, it does appear to be the case that the bug only occurs with hydroponic benches and not regular growing fields.

**Comment by OcrecOrg** [comment] 2021-07-18 11:33
Same Issue for me, until I build Hydroponics everything is fine, as soon as I build them it gives me the same error. If I remove the Hydroponics though it seems to be working.

**Comment by Raccoononi** [comment] 2021-08-30 22:19
The issue is still present in the latest build and the latest rimworld version (even unstable), logs attached here: https://gist.github.com/HugsLibRecordKeeper/6675c0ef1a685208d408a1abcd967f2d
A fairly long modlist but this should not be a problem as the issue is present in vanilla game
Scroll down to bottom to see job initiation spam

**Comment by Niilo007** [comment] 2021-09-22 13:14
Seems to be fixed in the 2.5.16 wip build.
i didnt do extensive testing, so unless it takes a while in game for it to break, it seems ok.
i didnt get errors and the crops got harvested just fine

**Closed** 2021-09-25 20:55 UTC
Labels: Bug, Reproducible, Vanilla RT, Game Breaking, Fixed In Preview, RT 2.5.15, RW 1.3.3104
