### ISSUE TITLE
Errors and Stutters regarding predator animal hunting job

### ISSUE THREAD

**Issue by Eldulac** [cseelhoff/RimThreaded#481] opened 2021-03-10 22:45 UTC
Using RimThreaded causes frequent errors and stutters whenever animals are performing certain Jobs. 
At least hunting, ingesting, wandering and hauling have caused these for both wild and tamed animals. This issue covers the predator animal hunting job error.

Edit: This issue was previously directed towards RimSeasoning, but after further testing it was found that the errors occur without it. Therefore, this is now a vanilla RimThreaded issue.

Steps to reproduce the behavior
1. Start a game on a big map
2. Speed up
3. Wait for predator animals to start hunting
4. Errors and stuttering should follow

**Logs**
https://gist.github.com/Eldulac/7951dc904f25788e19698201bbe7de17
https://gist.github.com/HugsLibRecordKeeper/f96540cf9768267ce5a4990655fa4fcc

**Save file**
[RimSeasoning Issue.zip](https://github.com/cseelhoff/RimThreaded/files/6119235/RimSeasoning.Issue.zip)

**Mod list**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Mod Manager
* RimThreaded

**Comment by pastorismylord** [comment] 2021-05-15 05:07
unable to reproduce error "animal hunting job" with 2.1.5 and 2 different save files. Further testing may be required.

**Comment by pastorismylord** [comment] 2021-05-15 05:24
unable to reproduce even when reducing the hunger of the animals via debug options. it may be fixed now.

**Closed** 2021-06-19 04:14 UTC
Labels: 1.3.1 - 1.3.2, Bug, Confirmed, Fixed In Preview, Reproducible, Vanilla RT
