### ISSUE TITLE
"Rim-Effect: Core" Can't priotize deconstruction of doors with Rim-effect installed 

### ISSUE THREAD

**Issue by RichardGubijev** [cseelhoff/RimThreaded#505] opened 2021-05-08 18:30 UTC
**Describe the bug**
Trying to deconstruct a door with Rim-effect and RimThreaded installed throws up an issue.  

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Build a door
2. Set to deconstruction
3. Prioritize it with a pawn

**Error Log**
https://gist.github.com/357a9533a4619c12baf4797ccc28c106

**Mod list (Sorry, it's mod manager)**
Version: 1
Name: Rim-effect-Rim-threaded-broken
Mods:
- Id: brrainz.harmony
  Name: Harmony
- Id: me.samboycoding.betterloading
  Name: BetterLoading
- Id: ludeon.rimworld
  Name: Core
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: fluffy.modmanager
  Name: Mod Manager
- Id: unlimitedhugs.hugslib
  Name: HugsLib
- Id: erdelf.humanoidalienraces
  Name: Humanoid Alien Races 2.0
- Id: neronix17.embrasures
  Name: '[O21] Seamless Embrasures'
- Id: cp.rimdeed
  Name: '[RH2] Rimdeed® - Pawn Recruitment'
- Id: madeline.modmismatchformatter
  Name: Better ModMismatch Window
- Id: fluffy.blueprints
  Name: Blueprints
- Id: nkuznia.buildnearanimatrees
  Name: Build Near Anima Trees
- Id: uuugggg.buildfrominventory
  Name: Build From Inventory
- Id: neceros.bulksmelting
  Name: Bulk Smelting
- Id: fuglypump.bulkstonecutting
  Name: Bulk Stonecutting
- Id: calltradeships.kv.rw
  Name: '[KV] Call Trade Ships'
- Id: smashphil.carrycapacityfixed
  Name: Carry Capacity Fixed
- Id: petetimessix.compacthediffs
  Name: Compact Hediffs
- Id: unlimitedhugs.defensivepositions
  Name: Defensive Positions
- Id: merthsoft.designatorshapes
  Name: Designator Shapes
- Id: dubwise.dubsmintmenus
  Name: Dubs Mint Menus
- Id: dubwise.dubsmintminimap
  Name: Dubs Mint Minimap
- Id: dubwise.dubsperformanceanalyzer
  Name: Dubs Performance Analyzer
- Id: edb.preparecarefully
  Name: EdB Prepare Carefully
- Id: wit.expandedroofing
  Name: Expanded Roofing
- Id: ancientgammoner.groundtargeter
  Name: Ground Targeter
- Id: notooshabby.homemover
  Name: Home Mover
- Id: taveron.increasedstack
  Name: Increased Stack
- Id: murmur.isid
  Name: Infestations Spawn in Darkness
- Id: mlie.inventorytab
  Name: InventoryTab (Continued)
- Id: krafs.levelup
  Name: Level Up!
- Id: ratys.madskills
  Name: Mad Skills
- Id: zylle.mapdesigner
  Name: Map Designer
- Id: neceros.metaldontburn
  Name: Metal Don't Burn
- Id: erdelf.minifyeverything
  Name: MinifyEverything
- Id: 4loris4.morelinkables
  Name: More Linkables
- Id: hobtook.mortaraccuracy
  Name: Mortar Accuracy
- Id: bar0th.nodebris
  Name: No Debris 1.1/1.2
- Id: doug.nojobauthors
  Name: No Job Authors
- Id: weilbyte.nopowerwires
  Name: No Power Wires
- Id: bar0th.norandomrelations
  Name: No Random Relations
- Id: mehni.numbers
  Name: Numbers
- Id: rimfridge.kv.rw
  Name: '[KV] RimFridge'
- Id: jaxe.rimhud
  Name: RimHUD
- Id: arandomkiwi.rimsaves
  Name: RimSaves
- Id: sandy.rpgstyleinventory
  Name: RPG Style Inventory
- Id: mobius.royaltytweaks
  Name: Royalty Tweaks
- Id: nmeijer.settlementinventory
  Name: Settlement Inventory
- Id: sf.grim.reality
  Name: SF Grim Reality
- Id: erdelf.showmoddesignators
  Name: ShowModDesignators
- Id: gguake.ui.simplesearchbar
  Name: Simple Search Bar
- Id: petetimessix.simplesidearms
  Name: Simple sidearms
- Id: sarg.smartspeed
  Name: Smart Speed
- Id: dhultgren.smarterconstruction
  Name: Smarter Construction
- Id: linkolas.stabilize
  Name: Stabilize
- Id: zhrocks11.stackablechunks
  Name: Stackable Chunks [Continued]
- Id: automatic.startupimpact
  Name: Startup impact
- Id: gt.sam.tilledsoil
  Name: Tilled Soil
- Id: timmyliang.tradehelper
  Name: TradeHelper
- Id: tradingspot.kv.rw
  Name: '[KV] Trading Spot'
- Id: murmur.walllight
  Name: Wall Light
- Id: bodlosh.weaponstats
  Name: WeaponStats
- Id: captainmuscles.whonext
  Name: Who's Next?
- Id: falconne.bwm
  Name: Better Workbench Management
- Id: unlimitedhugs.allowtool
  Name: Allow Tool
- Id: mlie.proximity
  Name: Proximity (Continued)
- Id: mrkociak.morearchotechstuffandthingsreupload
  Name: More Archotech Garbage Reupload
- Id: vanillaexpanded.vfecore
  Name: Vanilla Furniture Expanded
- Id: oskarpotocki.vanillafactionsexpanded.core
  Name: Vanilla Expanded Framework
- Id: rimeffect.core
  Name: 'Rim-Effect: Core'
- Id: majorhoff.rimthreaded
  Name: RimThreaded [1.2]
`

**Comment by 15adhami** [comment] 2021-05-09 02:43
Was able to reproduce error in 1.3.2: https://gist.github.com/HugsLibRecordKeeper/f9e6d7af141398a0446b14c6dc1d15c0.

Seems to be fixed in 2.0.7.

**Closed** 2021-06-19 04:14 UTC
Labels: 1.3.1 - 1.3.2, Bug, Confirmed, Fixed In Preview, Mod Incompatibility, Reproducible
