### ISSUE TITLE
Freeze when stressing game

### ISSUE THREAD

**Issue by davida1a2** [cseelhoff/RimThreaded#12] opened 2020-09-08 17:54 UTC
I tried to stress the game via adding lots and lots of raids. After 1 or 2 minutes there comes one red error and it freezes again.
Red error example: **Thread: 30 did not finish within 500ms. Continuing to tick other things.**
The number sometimes changes to a slightly different one (28 or sth)

I run a Ryzen 2700x (8 cores, 16 threads) and set thread count to 8.

The game runs fluid (sometimes red error messages, nothing significant) when i play normally.
Red error example: ** Detected infinite stat recursion when evaluating Hearing**
Hearing is sometimes replaced with other health conditions.

I have not tried a long playthrough yet.

I write this issue because maybe you use Intel instead of AMD, so maybe some problems are different on some CPUs.

**Comment by cseelhoff** [comment] 2020-09-08 18:06
Thank you for your bug testing and submission! I created a separate bug issue for the "Detected infinite stat recursion when evaluating".

As far as the "Thread: 30 did not finish within 5000ms. Continuing to tick other things..." - I added this in there for when one of the many threads takes more than 5000ms to finish. Normally this means I have some bad code causing an infinite loop. But since I don't want the game to crash for users, I just display an error and let the game continue. Unfortunately, as these threads continue to die, the game will perform slower.

You have almost certainly detected a bug. If you are able to reproduce it in a save file or some other set of actions fairly consistently, please let me know so I can debug. Thanks!

I can say that CPU make/model shouldn't matter, but as a side note, make sure you are setting the worker thread count in the mod options. 1-2 per CPU core is about right, but play around with the value to see what works best for you. A good way to measure is to download the mod TicksPerSecond.

**Comment by cseelhoff** [comment] 2020-09-10 03:47
Can you confirm if this is fixed now with version 1.0.3 or later?

**Comment by davida1a2** [comment] 2020-09-10 05:27
Unfortunately I'm not at home for a week. I tried it about 11 hours ago (I think version 1.0.2). The bug was still present back then.

**Closed** 2020-09-17 19:35 UTC
Labels: bug
