### ISSUE TITLE
Bestowing Ceremony does not work

### ISSUE THREAD

**Issue by ProvoGo** [cseelhoff/RimThreaded#147] opened 2020-09-25 14:57 UTC
Specs:
i7-6700K 4.00GHz
GTX 1070

Modlist:
Harmony
Core
Royalty
Rimthreaded (1.0.40)
TPS

Expected Behavior:
Bestowing ceremony is successful resulting in a tier 1 psychic.

Behavior:
When the pawn reaches the bestower it throws an error, while saying the bestowing ceremony has begun, but it doesn't actually begin.
Result not able to get the psychic powers.

Note: 
Seems like i cant reproduce it.
But i did find a fix, saving and reloading works

https://gist.github.com/ProvoGo/84b402a217d2a709e030031c3e9b1e2a

**Comment by Tschuangtse** [comment] 2020-09-26 09:29
Cannot confirm the bug, appears to be a "vanilla" bug. Wasn't able to reproduce it myself either.
I use an identical modlist, but load RimThreaded in Version 1.0.41 and after TPS.

**Comment by cseelhoff** [comment] 2020-11-23 04:41
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.

**Closed by cseelhoff** 2020-11-23 04:41 UTC
