### ISSUE TITLE
Colony vanishes (Could not resolve reference to object)

### ISSUE THREAD

**Issue by thefriendlycacti** [cseelhoff/RimThreaded#285] opened 2020-11-24 21:33 UTC
**Describe the bug**
all colonists stopped working and were unable to interact with anything they. They all just went on their normal wonder when there is nothing to do and I got an alert for every colonist that there was nothing to do. When I reloaded save I was booted to the world screen and got a nice solid error log
It seems that only my colony vanished, save data still seems to have the rest of the world's data.

Here are the save files(one being the last autosave before it broke and one being the save I took after all my colonists stopped working)
[savefiles.zip](https://github.com/cseelhoff/RimThreaded/files/5592862/savefiles.zip)

**To Reproduce**
No known way

**Error Logs**
when loading the broken save file
https://gist.github.com/f8bae3026b881a349295a3f319482caa

Logfile of when colonists stopped working before reloading the map
https://gist.github.com/thefriendlycacti/a1287d97b594132494b13d2736a232a3

**Mod List**
https://gist.github.com/thefriendlycacti/100a1eff20f09a80a4a5988b407fabf9

**Screenshots**
![image](https://user-images.githubusercontent.com/13293946/100153846-90b9e100-2e59-11eb-8827-5dec2afdf899.png)

**Comment by MartinaMartes** [comment] 2020-12-07 08:09
https://gist.github.com/HugsLibRecordKeeper/7f407fd2674329c562f2d7d0ddd803d4
Same issue . happend same way . Sadly cannot replicate

**Comment by cseelhoff** [comment] 2021-02-04 18:06
I did do some patches around "Verse.AI.RegionCostCalculatorWrapper" so this may be fixed... Please make another post if this reoccurs. Otherwise this will probably be closed in the next week or so, since its sounds like this is not reproducible.

**Comment by pastorismylord** [comment] 2021-02-04 22:44
unable to reproduce the issue on 1.3.1

**Comment by Niilo007** [comment] 2021-02-09 11:55
https://gist.github.com/d17dd2e352dd23e2d335a0101be1e0db

happened to me in a modded game. log is linked.
re opening with new tags

**Comment by Niilo007** [comment] 2021-02-09 12:06
[Empire3 (Permadeath).zip](https://github.com/cseelhoff/RimThreaded/files/5951218/Empire3.Permadeath.zip)

save file is attached

**Comment by BlazingPL** [comment] 2021-06-27 22:08
Also happening on RT 2.4.2 on loading previously fine save. 
[https://pastebin.com/WyaCp2FM](url)

**Comment by cseelhoff** [comment] 2021-08-17 14:09
Please retest with RT>=2.5.12 and include steps to reproduce. Closing until then.

**Closed by cseelhoff** 2021-08-17 14:09 UTC
Labels: Bug, Accepted For Testing, Confirmed, Game Breaking, 1.3.X.X, 2.4.X.X, 2.4.2.0
