### ISSUE TITLE
Could not load UnityEngine.Texture2D

### ISSUE THREAD

**Issue by GervyMaglina** [cseelhoff/RimThreaded#194] opened 2020-10-15 12:08 UTC
Issue can be triggered by walking your pawn or melee attacking each other. Found out Humanoid Alien Races 2.0 caused the error to happen.

https://gist.github.com/GervyMaglina/b065cceb23fe8525ba1d080fe0843b6b

Loaded Mod -
    Harmony
    Core
    RimThreaded
    Hugslib
    **Humanoid Alien Races 2.0**
    Mod Manager

**Comment by drunken-dwarf** [comment] 2020-10-18 08:21
Duplicate of https://github.com/cseelhoff/RimThreaded/issues/94?

**Comment by GervyMaglina** [comment] 2020-10-20 04:35
yeah. It can be triggered if you just wait without doing anything while the game is running.

**Closed** 2020-11-02 11:30 UTC
