### ISSUE TITLE
(2.2.19) Pod launchers aren't working

### ISSUE THREAD

**Issue by Courier6Lau** [cseelhoff/RimThreaded#527] opened 2021-05-30 07:29 UTC
When trying to use the pod launchers and launching the drop pods into the world tile the game refuse to do it saying "Beyond maximum range". the only time it works is if you only drop it within your colony.

*Steps to reproduce the behavior* 
1. Place a pod launcher and a drop pod
2. Fuel it
3. Send it to a world tile

It does not produce an error log it just says "Beyond maximum range" in game.
![image](https://user-images.githubusercontent.com/85052635/120095942-4f352600-c15b-11eb-8864-2c552f88e2ef.png)

*Save file*
[Debugtransport.zip](https://github.com/cseelhoff/RimThreaded/files/6566632/Debugtransport.zip)

Mod list 
* Harmony
* Core
* HugsLib
* RimThreaded (2.2.19)

**Comment by pastorismylord** [comment] 2021-05-30 16:36
@Courier6Lau can you please add a savegame showing the issue?

**Comment by Courier6Lau** [comment] 2021-05-30 17:36
Added a savegame on where i tested it.

**Comment by 15adhami** [comment] 2021-05-31 14:19
Confirmed in 2.2.19. Tested on a new save file, created a pod launcher and a transport pod, filled the fuel, and tried to launch to a tile. It says "Beyond maximum range".

**Comment by pastorismylord** [comment] 2021-06-07 21:45
https://github.com/cseelhoff/RimThreaded/issues/531 is a duplicate of this issue, it mentions the issue may be on WolrdTargeter

**Comment by pastorismylord** [comment] 2021-06-07 21:54
this one may be related as well: https://github.com/cseelhoff/RimThreaded/issues/529 it could all be related to WorldTargeter

**Comment by cseelhoff** [comment] 2021-06-17 23:10
Seems to work fine for me in 2.3.6

**Comment by pO0P3R125** [comment] 2021-06-18 00:21
now working

**Closed** 2021-06-19 00:59 UTC
Labels: 2.1.1 - X.X.X, Bug, Game Breaking, Reproducible, Vanilla RT
